# Generated by Django 2.2.5 on 2019-09-07 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='picture_primary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Picture'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='product.Picture'),
        ),
        migrations.AlterField(
            model_name='module',
            name='pictures',
            field=models.ManyToManyField(blank=True, related_name='modules', to='product.Picture'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='pictures',
            field=models.ManyToManyField(blank=True, related_name='variations', to='product.Picture'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
